"use client";
// import Proiders from "@/Providers/providers"; // work
import "./globals.css";
import { SessionProvider } from "next-auth/react";
export const metadata = {
  title: "next auth with github",
  description: "Generated by create next app",
};

// export default async function RootLayout({ // Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
